![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [8]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [10]:
print(my_array[-8:-11:-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
matrix_inv = np.flipud(np.fliplr(my_matrix)) #o my_matrix[::-1,::-1] o np.flip
print(matrix_inv)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [13]:
my_matrix1 = my_matrix[:2,:2]
print(my_matrix1)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [14]:
my_matrix2 = my_matrix[:5:2,:5:2]
print(my_matrix2)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [15]:
my_matrix3 = my_matrix[:3,::-1]
print(my_matrix3)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [16]:
print(np.flip(my_matrix[:3,:5],axis=1))

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [17]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [18]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [19]:
x1= np.fromiter((element for element in x if element == 'Loro'), dtype=x.dtype)
print(x1)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [20]:
ejer_9 = np.random.randint(0,10,size=(2,5,2))
print(ejer_9)

[[[1 0]
  [9 5]
  [0 0]
  [6 5]
  [1 9]]

 [[5 9]
  [8 2]
  [4 3]
  [8 0]
  [6 7]]]


In [ ]:
#np.arange(20) y luego ejer_9.reshape(2,5,2)

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [21]:
ejer_10 = my_matrix[::-1,::-1]
print(ejer_10)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [22]:
ejer_11 = np.zeros(10)
print(ejer_11.nbytes)

80


In [23]:
ejer_11[3] = 1
print(ejer_11)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [24]:
ejer_12 = np.arange(10,50)
ejer_12=ejer_12[::-1]
print(ejer_12)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [25]:
def ejer_13(vector) :
    return np.where(vector != 0)

In [26]:
print(ejer_13(np.array([1,2,0,0,4,0])))

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [41]:
ejer_14 = np.random.randint(100, size=100).reshape(10,10)
print(ejer_14)

[[73 67 77 54 24 26 37  8 37 92]
 [41  5 65 70 69 91 12 92 17 33]
 [12 83 74 48 47  1 32  9 89 43]
 [81 18 23 36 35 61 82 43 88 44]
 [33 34  9 24 81 20 33 78 89 72]
 [58 60 64 72 17 42 73 23  4 75]
 [56 34 82 92 33 16 32  5 39 37]
 [97 74 18 23 78 44 56 36 45 82]
 [80 41 52 59 23  1 84 47 19  3]
 [25 90 67 86 41 76 14 40 42 91]]


In [42]:
print(ejer_14.min(), ejer_14.max())

1 97


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [27]:
ejer_15 = np.random.randint(1,40, size=30)
print(ejer_15)

[15  7 18 29 15 14 28 30 29  9  6  3  3 14 27 25 23  7 33 14 27 36 17 31
  2  7 16 18 39 28]


In [28]:
ejer_15.mean()

19.0

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [92]:
ejer_16 = np.ones((4,4))
ejer_16[1:3,1:3] = 0
print(ejer_16)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [98]:
ejer_17 = np.zeros((8,8))
ejer_17[::2,1::2] = 1
ejer_17[1::2,::2] = 1
print(ejer_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [103]:
ejer_18 = np.array([[0,1],[1,0]])
ejer_18 = np.tile(ejer_18, (4,4))
print(ejer_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [104]:
ejer_19 = np.random.randint(1,20, (5,5))
print(ejer_19)

[[15  2 18  2 10]
 [18  5 15  5 18]
 [10 14  4 14  9]
 [ 1 10 11  7  4]
 [14  7 17  8  7]]


In [105]:
ejer_19 = (ejer_19 - np.mean(ejer_19)) / np.std(ejer_19)
print(ejer_19)

[[ 0.98130676 -1.47196014  1.54744528 -1.47196014  0.03774257]
 [ 1.54744528 -0.90582163  0.98130676 -0.90582163  1.54744528]
 [ 0.03774257  0.79259392 -1.09453447  0.79259392 -0.15097027]
 [-1.66067298  0.03774257  0.22645541 -0.52839595 -1.09453447]
 [ 0.79259392 -0.52839595  1.35873244 -0.33968311 -0.52839595]]


In [106]:
print(ejer_19.mean())
print(ejer_19.std())

-1.0658141036401502e-16
1.0


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [112]:
ejer_20 = np.arange(11)
print(ejer_20)
y = ejer_20.copy()
y[(y > 3) & (y < 8)] = -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [114]:
z = ejer_20.copy()
z[(z > 3) & (z < 8)]*=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
